# Composite action that installs LHAPDF in a given environment
name: "Install LHAPDF in a Poetry env"

description: "Install LHAPDF given some Inputs"

inputs:
  prefix:
    description: "Prefix of Poetry env"
    required: true
  pyversion:
    description: "Python version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      run: |
        echo "${{ inputs.prefix }}/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=${{ inputs.prefix }}/lib" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=${{ inputs.prefix }}/lib/pkgconfig" >> $GITHUB_ENV
        echo "PYTHONPATH=${{ inputs.prefix }}/lib/python${{ inputs.pyversion }}/site-packages" >> $GITHUB_ENV
      shell: bash

    - name: Install LHAPDF
      env:
        VERSION: 6.5.3
      run: |
        # Download lhapdf
        wget --no-verbose https://lhapdf.hepforge.org/downloads/?f=LHAPDF-${VERSION}.tar.gz -O LHAPDF-${VERSION}.tar.gz
        tar xzf LHAPDF-${VERSION}.tar.gz
        cd LHAPDF-${VERSION}

        # Configure & install
        autoreconf -f -i
        PYTHON="${{ inputs.prefix }}/bin/python3" ./configure --prefix=${{ inputs.prefix }}
        touch wrappers/python/lhapdf.pyx
        make clean
        make -j
        make install
        cd ..
      shell: bash
