# Composite action that installs LHAPDF in a given environment
name: "Install LHAPDF in a Poetry env"

description: "Install LHAPDF given some Inputs"

inputs:
  prefix:
    description: "Prefix of Poetry env"
    required: true
  pyversion:
    description: "Python versions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      run: |
        echo "${{ inputs.prefix }}/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=${{ inputs.prefix }}/lib" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=${{ inputs.prefix }}/lib/pkgconfig" >> $GITHUB_ENV
        echo "PYTHONPATH=${{ inputs.prefix }}/lib/python${{ inputs.pyversion }}/site-packages" >> $GITHUB_ENV
      shell: bash

    - name: Install LHAPDF 6.4.0
      env:
        VERSION: 6.4.0
      run: |
        wget --no-verbose https://lhapdf.hepforge.org/downloads/?f=LHAPDF-${VERSION}.tar.gz -O LHAPDF-${VERSION}.tar.gz
        tar xzf LHAPDF-${VERSION}.tar.gz
        cd LHAPDF-${VERSION}
        touch wrappers/python/lhapdf.pyx
        PYTHON="${{ inputs.prefix }}/bin/python3" ./configure --prefix=${{ inputs.prefix }}
        make clean
        make -j
        make install
        cd ..
      shell: bash

    # - name: Install PDF sets
    #   run : |
    #     lhapdf update
    #     lhapdf install NNPDF40_nnlo_as_01180
    #   shell: bash
