############################################################
# Configuration file for nnufit
############################################################

description: runcard for nnufit

# Datasets to be included in the fit
experiments:
- {dataset: BEBCWA59_F2, frac: 0.75}
- {dataset: BEBCWA59_F3, frac: 0.75}
- {dataset: CCFR_F2, frac: 0.75}
- {dataset: CCFR_F3, frac: 0.75}
- {dataset: CDHSW_DXDYNUB, frac: 0.75}
- {dataset: CDHSW_DXDYNUU, frac: 0.75}
- {dataset: CDHSW_F2, frac: 0.75}
- {dataset: CDHSW_F3, frac: 0.75}
- {dataset: CDHSW_FW, frac: 0.75}
- {dataset: CHARM_F2, frac: 0.75}
- {dataset: CHARM_F3, frac: 0.75}
- {dataset: CHORUS_DXDYNUB, frac: 0.75}
- {dataset: CHORUS_DXDYNUU, frac: 0.75}
- {dataset: CHORUS_F2, frac: 0.75}
- {dataset: CHORUS_F3, frac: 0.75}
- {dataset: NUTEV_DXDYNUB, frac: 0.75}
- {dataset: NUTEV_DXDYNUU, frac: 0.75}
- {dataset: NUTEV_F2, frac: 0.75}
- {dataset: NUTEV_F3, frac: 0.75}
- {dataset: BEBCWA59_F2_MATCHING, frac: 0.75}
- {dataset: BEBCWA59_F3_MATCHING, frac: 0.75}
- {dataset: CCFR_F2_MATCHING, frac: 0.75}
- {dataset: CCFR_F3_MATCHING, frac: 0.75}
- {dataset: CDHSW_DXDYNUU_MATCHING, frac: 0.75}
- {dataset: CDHSW_DXDYNUB_MATCHING, frac: 0.75}
- {dataset: CDHSW_F2_MATCHING, frac: 0.75}
- {dataset: CDHSW_F3_MATCHING, frac: 0.75}
- {dataset: CDHSW_FW_MATCHING, frac: 0.75}
- {dataset: CHORUS_DXDYNUB_MATCHING, frac: 0.75}
- {dataset: CHORUS_DXDYNUU_MATCHING, frac: 0.75}
- {dataset: CHORUS_F2_MATCHING, frac: 0.75}
- {dataset: CHORUS_F3_MATCHING, frac: 0.75}
- {dataset: NUTEV_DXDYNUB_MATCHING, frac: 0.75}
- {dataset: NUTEV_DXDYNUU_MATCHING, frac: 0.75}
- {dataset: NUTEV_F2_MATCHING, frac: 0.75}
- {dataset: NUTEV_F3_MATCHING, frac: 0.75}

# Define some kinematic cuts (Omit if not needed)
W2min: 3.5

# chi2 history stored for each `log_freq` epochs
log_freq: 100

# True: fit to pseudodata, False: fit to central values
genrep: True

# Various seed values
global_seeds: 456
trvlseed: 123
pseudodataseed: 2

# Define Neural Network Parameters
fit_parameters:
  epochs: 20000
  stopping_patience: 5000
  units_per_layer: [20,15,10]
  activation_per_layer: [sigmoid, tanh, sigmoid]
  optimizer_parameters:
    optimizer: Adam
    clipnorm: 1.0e-6
    learning_rate: 5.0e-4
  feature_scaling: True
  val_chi2_threshold: 400
  initializer_seed: 1
