############################################################
# Configuration file for nnufit
############################################################

description: runcard for nnufit

# Datasets to be included in the fit
experiments:
- {dataset: BEBCWA59_F2, frac: 0.75}
- {dataset: BEBCWA59_F3, frac: 0.75}
- {dataset: CCFR_F2, frac: 0.75}
- {dataset: CCFR_F3, frac: 0.75}
- {dataset: CDHSW_DXDYNUB, frac: 0.75}
- {dataset: CDHSW_DXDYNUU, frac: 0.75}
- {dataset: CDHSW_F2, frac: 0.75}
- {dataset: CDHSW_F3, frac: 0.75}
- {dataset: CDHSW_FW, frac: 0.75}
- {dataset: CHARM_F2, frac: 0.75}
- {dataset: CHARM_F3, frac: 0.75}
- {dataset: CHORUS_DXDYNUB, frac: 0.75}
- {dataset: CHORUS_DXDYNUU, frac: 0.75}
- {dataset: CHORUS_F2, frac: 0.75}
- {dataset: CHORUS_F3, frac: 0.75}
- {dataset: NUTEV_DXDYNUB, frac: 0.75}
- {dataset: NUTEV_DXDYNUU, frac: 0.75}
- {dataset: NUTEV_F2, frac: 0.75}
- {dataset: NUTEV_F3, frac: 0.75}

# Define some kinematic cuts (Omit if not needed)
W2min: 3.5

# chi2 history stored for each `log_freq` epochs
log_freq: 100

# True: fit to pseudodata, False: fit to central values
genrep: True

# Various seed values
global_seeds: 456
trvlseed: 123
pseudodataseed: 2

# Define Neural Network Parameters
fit_parameters:
  epochs: 50000
  stopping_patience: 15000
  units_per_layer: [70, 55, 40, 20, 20]
  activation_per_layer: [tanh, tanh, tanh, tanh, selu]
  optimizer_parameters:
    optimizer: Adam
    clipnorm: 0.00001
    learning_rate: 0.05
  feature_scaling: True
  val_chi2_threshold: 4
  initializer_seed: 1
