############################################################
# Configuration file for nnufit
############################################################

description: runcard for nnufit

# Datasets to be included in the fit
experiments:
- {dataset: BEBCWA59_F2, frac: 0.75}
- {dataset: BEBCWA59_F3, frac: 0.75}
- {dataset: CCFR_F2, frac: 0.75}
- {dataset: CCFR_F3, frac: 0.75}
- {dataset: CDHSW_DXDYNUB, frac: 0.75}
- {dataset: CDHSW_DXDYNUU, frac: 0.75}
- {dataset: CDHSW_F2, frac: 0.75}
- {dataset: CDHSW_F3, frac: 0.75}
- {dataset: CDHSW_FW, frac: 0.75}
- {dataset: CHARM_F2, frac: 0.75}
- {dataset: CHARM_F3, frac: 0.75}
- {dataset: CHORUS_DXDYNUB, frac: 0.75}
- {dataset: CHORUS_DXDYNUU, frac: 0.75}
- {dataset: CHORUS_F2, frac: 0.75}
- {dataset: CHORUS_F3, frac: 0.75}
- {dataset: NUTEV_DXDYNUB, frac: 0.75}
- {dataset: NUTEV_DXDYNUU, frac: 0.75}
- {dataset: NUTEV_F2, frac: 0.75}
- {dataset: NUTEV_F3, frac: 0.75}
# -- PROTON BC DATASETS (Matching A=1) --
- {dataset: PROTONBC_F2_MATCHING, frac: 0.75}
- {dataset: PROTONBC_F3_MATCHING, frac: 0.75}
- {dataset: PROTONBC_DXDYNUU_MATCHING, frac: 0.75}
- {dataset: PROTONBC_DXDYNUB_MATCHING, frac: 0.75}
# -- MATCHING AT HIGH Q2 --
- {dataset: BEBCWA59_F2_MATCHING, frac: 0.75}
- {dataset: BEBCWA59_F3_MATCHING, frac: 0.75}
- {dataset: CCFR_F2_MATCHING, frac: 0.75}
- {dataset: CCFR_F3_MATCHING, frac: 0.75}
# - {dataset: CDHSW_DXDYNUU_MATCHING, frac: 0.75}
# - {dataset: CDHSW_DXDYNUB_MATCHING, frac: 0.75}
# - {dataset: CDHSW_F2_MATCHING, frac: 0.75}
# - {dataset: CDHSW_F3_MATCHING, frac: 0.75}
# - {dataset: CDHSW_FW_MATCHING, frac: 0.75}
- {dataset: CHORUS_DXDYNUB_MATCHING, frac: 0.75}
- {dataset: CHORUS_DXDYNUU_MATCHING, frac: 0.75}
- {dataset: CHORUS_F2_MATCHING, frac: 0.75}
- {dataset: CHORUS_F3_MATCHING, frac: 0.75}
- {dataset: NUTEV_DXDYNUB_MATCHING, frac: 0.75}
- {dataset: NUTEV_DXDYNUU_MATCHING, frac: 0.75}
- {dataset: NUTEV_F2_MATCHING, frac: 0.75}
- {dataset: NUTEV_F3_MATCHING, frac: 0.75}

# Define some kinematic cuts (Omit if not needed)
W2min: 3.5

# chi2 history stored for each `log_freq` epochs
log_freq: 5000

# True: fit to pseudodata, False: fit to central values
genrep: True

# True: rescale the input kinematics
rescale_inputs: True

# Various seed values
global_seeds: 1865683875

# Parameter space to be scanned
hyperscan:
  optimizers:
    - Adam
    - Nadam
    - RMSprop
  clipnorms:
    - 0.000100
    - 0.000010
    - 0.000001
  initial_lr:
    - 0.100
    - 0.010
    - 0.001
  number_layers:
    min: 2
    max: 5
  number_nodes:
    min: 10
    max: 150
  activations:
    - tanh
    - relu
    - selu
    - sigmoid
  activations_output:
    - linear
    - relu
    - selu

# Define Neural Network Parameters
fit_parameters:
  epochs: 500
  print_rate: 100
  stopping_patience: 5000
  units_per_layer: None
  activation_per_layer: None
  optimizer_parameters:
    optimizer: None
    clipnorm: None
    learning_rate: None
  val_chi2_threshold: 10
  small_x_exponent:
      f2nu  : [0.25, 2.0]
      flnu  : [0.25, 2.0]
      xf3nu : [0.25, 2.0]
      f2nub : [0.25, 2.0]
      flnub : [0.25, 2.0]
      xf3nub: [0.25, 2.0]
