#
# Configuration file for nnufit
#
############################################################
description: A first trial fit with nnufit

experiments:
- {dataset: NUTEV_F2, frac: 0.75}
- {dataset: NUTEV_F3, frac: 0.75}

trvlseed: 1
pseudodataseed: 1

fit_parameters:
  epochs: 17000
  stopping_patience: 0.1
  units_per_layer: [25, 20]
  activation_per_layer: [tanh, tanh]
  optimizer:
    clipnorm: 1e-5
    learning_rate: 1e-3
    optimizer_name: Adam
  initializer_seed: 1